
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package supernotes;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import supernotes.helpers.InputScanner;

import java.io.*;
        import java.sql.SQLException;
import java.util.Arrays;
import java.util.Collection;
import java.util.Scanner;

import static org.junit.Assert.assertTrue;
import static org.junit.Assert.assertEquals;

@RunWith(Parameterized.class)
public class NotionTest {

    private String command;
    private String expectedOutput;

    public NotionTest(String command, String expectedOutput) {
        this.command = command;
        this.expectedOutput = expectedOutput;
    }

    @Parameterized.Parameters
    public static Collection<Object[]> data() {
        return Arrays.asList(new Object[][] {
                { "sn notion create \"Contenu de la nouvelle page\"\nsecret_VYciXSiKdbTEcjFkDTJLuBniaGvBgtvWgcqST4Ji99N\nexit\n", "Note ajoutée avec succès" }
        });
    }


    @Test
    public void TestAddNoteCommandsWithNotion() throws SQLException, IOException {
        // Define input
        String input = this.command;

        // Capture output
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outputStream));

        // Set up System.in with simulated input
        InputStream inputStream = new ByteArrayInputStream(input.getBytes());
        System.setIn(inputStream);
        InputScanner.setInstance(new Scanner(inputStream));

        try {
            App.main(new String[0]);

            String actualOutput = outputStream.toString().trim();
            inputStream.close();
            outputStream.close();

            assertTrue(actualOutput.contains(this.expectedOutput));

        } catch (Exception e) {
            assertTrue("Unexpected exception thrown: " + e.getMessage(), false);
            throw e;
        }
    }

}
