= ```SuperNote``` Documentation

== Choix du Sujet

Le choix de développer SuperNote en tant que plugin de gestion de notes orienté ligne de commande découle de plusieurs considérations. Tout d'abord, il existe déjà une multitude d'applications de prise de notes sur le marché. Cependant, beaucoup de ces solutions se concentrent sur une interface graphique utilisateur (GUI), offrant une expérience intuitive mais parfois moins efficiente pour les utilisateurs expérimentés de la ligne de commande ou pour ceux qui privilégient l'efficacité dans leur flux de travail.

En choisissant la ligne de commande comme interface principale, SuperNote vise à répondre aux besoins des utilisateurs habitués à cette méthode d'interaction. Cela permet également une intégration plus fluide avec divers environnements, notamment les outils de développement où la ligne de commande reste un élément central pour de nombreux utilisateurs. De plus, en s'appuyant sur une approche polyvalente, SuperNote cherche à offrir une solution unifiée pour la gestion de notes, pouvant s'intégrer harmonieusement avec différentes plateformes de prise de notes existantes et des outils de productivité variés.

== Concurrence

La concurrence sur le marché des applications de gestion de notes est significative, avec plusieurs solutions bien établies telles qu'Evernote, OneNote, Notion, et bien d'autres. Ces applications offrent une variété de fonctionnalités de prise de notes, de gestion de tâches, d'intégration multiplateforme et de collaboration. Certaines se concentrent sur des fonctionnalités spécifiques telles que l'intégration avec des outils de productivité, la prise en charge des médias riches, ou la facilité d'utilisation pour les équipes.

Cependant, SuperNote se distingue par son approche axée sur la ligne de commande, offrant une interface rapide et directe pour la gestion des notes, en particulier pour les utilisateurs à l'aise avec cette méthode d'interaction. Sa flexibilité pour s'intégrer avec diverses plates-formes de prise de notes existantes, ainsi qu'avec des environnements de développement, vise à fournir une expérience de prise de notes unifiée et fluide pour les utilisateurs exigeants en matière de productivité.

== Modèles

= Installation de SuperNote

== Prérequis

Avant d'utiliser SuperNote, assurez-vous que votre système remplit les conditions suivantes :

- **Java :** SuperNote nécessite une installation de Java (version 21) sur votre système. Assurez-vous que Java est correctement installé et configuré.
[source, shell]
----
java -version
----

- **Gradle :** SuperNote nécessite une installation de Gradle (version 8.4) sur votre système. Assurez-vous que Gradle est correctement installé et configuré.
[source, shell]
----
gradle -version
----

- **Environnement de Ligne de Commande :** Étant une application basée sur la ligne de commande, SuperNote nécessite un environnement de ligne de commande fonctionnel sur votre système.

- **Git (optionnel) :** Pour cloner le dépôt Git de SuperNote et obtenir la dernière version du code source, vous pouvez installer Git si vous souhaitez accéder au code directement depuis le dépôt GitHub.

Assurez-vous de remplir ces conditions préalables avant de continuer avec l'installation et l'utilisation de SuperNote.

== Lancement de l'Application

Pour lancer SuperNote, suivez ces étapes :

1. **Cloner le Projet :** Clonez le répertoire du projet SuperNote sur votre machine locale en utilisant la commande suivante :
[source, shell]
----
git clone https://github.com/dounyaa/SuperNotes.git
----

2. **Accéder au Répertoire :** Naviguez vers le répertoire du projet SuperNote.
[source, shell]
----
cd SuperNote
----

3. **Compiler le Code :** Compilez le code source de SuperNote en utilisant Gradle.
- Sous (macOS/Linux)
[source, shell]
----
./gradlew build
----

- Sous Windows
[source, shell]
----
gradlew.bat build
----

3. **Exécuter l'Application :** Lancez l'application SuperNote.
- Sous (macOS/Linux)
[source, shell]
----
./gradlew run
----

- Sous Windows
[source, shell]
----
gradlew.bat run
----

== Utilisation
Pour utiliser SuperNote, voici quelques commandes courantes que vous pouvez exécuter une fois l'application lancée depuis votre terminal :

- **Ajouter une Note :** Pour ajouter une nouvelle note, utilisez la commande suivante :
[source, shell]
----
  sn add "Contenu de la note" --tag "tag"
----

- **Exporter les Notes :** Pour exporter vos notes dans un fichier de format pdf, utilisez la commande :
[source, shell]
----
  sn export --all "chemin/vers/fichier.pdf"
----

- **Fermer l'Application :**
    ```bash
    exit
    ```



== Diagramme de classe 

----
@startuml
interface Note {
    +getContent(): String
    +setContent(content: String): void
}

class TextNote {
    -content: String
    -tag: String
    +getContent(): String
    +setContent(content: String): void
    +getTag(): String
    +setTag(tag: String): void
}

class ImageNote {
    -content: byte[]
    -tag: String
    +getContent(): byte[]
    +setContent(content: byte[]): void
    +getTag(): String
    +setTag(tag: String): void
}

interface NoteFactory {
    +createNote(): Note
}

class TextNoteFactory {
    +createNote(): Note
}

class ImageNoteFactory {
    +createNote(): Note
}

interface INoteManager {
    +addNote(Note: note): void
    +deleteByTag(Strin: tag): void
}

class NoteManager implements INoteManager {
    +addNote(Note: note): void
    +deleteByTag(Strin: tag): void
}


interface FileHandler {
    +exportPdfFile(String: filePath): void 
    +exportPdfFileUsingFilter(String: filePath, String: filter): void

}

class FileManager implements FileHandler {
    +exportPdfFile(String: filePath): void 
    +exportPdfFileUsingFilter(String: filePath, String: filter): void
    +exportPdf(String: filePath, List<Note>: result): void

}


class CommandLineInterface {
    +parseCommand(command: String): void
}

interface DBManager{
    +createNotesTable(): void
    +ddTextNote(String: content, String: tag): void
    +addImageNote(byte[]: imageBytes, String: tag): void
    +deleteNoteByTag(String: tag): void
    +getAllNotes(): ArrayList<Note> 
    +getAllNotesByTag(String: tag): ArrayList<Note> 
    +getAllNotesLike(String: contentMotif): ArrayList<Note> 
}

class SQLiteDBManager implements DBManager {
    +createNotesTable(): void
    +ddTextNote(String: content, String: tag): void
    +addImageNote(byte[]: imageBytes, String: tag): void
    +deleteNoteByTag(String: tag): void
    +getAllNotes(): ArrayList<Note>
    +getAllNotesByTag(String: tag): ArrayList<Note>
    +getAllNotesLike(String: contentMotif): ArrayList<Note>
    +connect(): void
    +getConnection(): void
    }

Note <|.. TextNote
Note <|.. ImageNote

NoteFactory <|.. TextNoteFactory
NoteFactory <|.. ImageNoteFactory
FileManager ..> DBManager
NoteManager ..> DBManager

NoteFactory ..> Note : creates
NoteManager ..> Note : manages
FileHandler ..> Note : handles


CommandLineInterface ..> NoteManager : sendsCommands

@enduml

----